trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: terraformConfigDirectory
  value: 'D:\azdvpsgit\dvpsfordetnetwebapp'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    cd $(terraformConfigDirectory) # Add a closing parenthesis here
    terraform init
    terraform plan -out=tfplan -input=false
  displayName: 'Terraform Init and Plan'

- script: |
    cd $(terraformConfigDirectory) # Add a closing parenthesis here
    terraform apply -input=false tfplan
  displayName: 'Terraform Apply'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(terraformConfigDirectory)' # Remove the "cd" command here
    artifactName: 'drop'
