trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    cd $(System.DefaultWorkingDirectory)/D:\azdvpsgit\dvpsfordetnetwebapp
    terraform init
    terraform plan -out=tfplan -input=false
  displayName: 'Terraform Init and Plan'

- script: |
    cd $(System.DefaultWorkingDirectory)/D:\azdvpsgit\dvpsfordetnetwebapp
    terraform apply -input=false tfplan
  displayName: 'Terraform Apply'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/D:\azdvpsgit\dvpsfordetnetwebapp'
    artifactName: 'drop'
