trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    # Clone the Git repository containing your Terraform configuration files
    git clone https://github.com/Gopikumar14/terraform-files.git $(System.DefaultWorkingDirectory)/terraform-config
    
    # Navigate to the directory where the files are cloned
    cd $(System.DefaultWorkingDirectory)/terraform-config
    
    terraform init -backend-config="access_key=$(azureServiceConnection.servicePrincipalId)"
    terraform plan -out=tfplan -input=false
  displayName: 'Terraform Init and Plan'

- script: |
    cd $(System.DefaultWorkingDirectory)/terraform-config
    terraform apply -input=false tfplan
  displayName: 'Terraform Apply'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/terraform-config'
    artifactName: 'drop'
